name: Checks

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Audit
        run: |
          npm run audit
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
